# @package _global_

defaults:
  - _self_

seed: 13
dataset_repo_id: aractingi/pick_place_lego_cube_1
train_split_proportion: 0.8

# Required by logger
env:
  name: "classifier"
  task: "binary_classification"


training:
  num_epochs: 20
  batch_size: 256
  learning_rate: 3e-4
  num_workers: 0
  grad_clip_norm: 10
  use_amp: true
  log_freq: 1
  eval_freq: 1  # How often to run validation (in epochs)
  save_freq: 10  # How often to save checkpoints (in epochs)
  save_checkpoint: true
  image_keys: ["observation.images.top", "observation.images.wrist"]
  label_key: "next.reward"

eval:
  batch_size: 16
  num_samples_to_log: 30  # Number of validation samples to log in the table

policy:
  name: "hilserl/classifier/pick_place_lego_cube_1"
  model_name: "lilkm/resnet10_without_pooling"
  model_type: "cnn"
  num_cameras: 2 # Has to be len(training.image_keys)

wandb:
  enable: true
  project: "classifier-training"
  job_name: "classifier_training_0"
  disable_artifact: false

device: "cuda"
resume: false
output_dir: "outputs/classifier"
